---
galaxy_info:
  role_name: nexus
  author: Jeannette
  description: Setup nexus in your environment.
  company: "DSG"
  issue_tracker_url: https://github.com/aem-design/ansible-role-nexus/issues
  license: Apache 2.0
  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - aem
    - cms
    - web
    - aemdesign
    - nexus
